# Generated by Django 2.1.5 on 2020-04-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150, verbose_name='Cargo')),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('begin_date', models.DateField(verbose_name='Fecha contratación')),
                ('end_date', models.DateField(verbose_name='Fecha término contrato')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-created'],
            },
        ),
    ]
